<a href="https://colab.research.google.com/github/yeshaswiniarjula/IDS_project/blob/main/sentinelNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv to Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Wednesday-workingHours.pcap_ISCX.csv to Wednesday-workingHours.pcap_ISCX.csv


wednesday working hours

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("Wednesday-workingHours.pcap_ISCX.csv")
print("Original Shape:", df.shape)
# Clean column names
df.columns = df.columns.str.strip()
# 2. Data Cleaning
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
print("After Cleaning Shape:", df.shape)
# 3. Check Label Distribution
print("\nLabel Counts:")
print(df['Label'].value_counts())
# 4. Convert Label to Binary
# BENIGN = 0, Attack = 1
df['Label'] = df['Label'].apply(lambda x: 0 if x == "BENIGN" else 1)
# 5. Separate Features and Target
X = df.drop('Label', axis=1)
y = df['Label']
# 6. Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# 7. Train-Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=42)
print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)
# 8. Train Random Forest Model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)
# 9. Predictions
y_pred = model.predict(X_test)
# Show first 10 predictions
print("\nFirst 10 Predictions:")
for i in y_pred[:10]:
    if i == 1:
        print("YES - Attack")
    else:
        print("NO - Normal")
# 10. Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print("\nModel Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("\nConfusion Matrix:\n", cm)
print("\nFull Classification Report:\n")
print(classification_report(y_test, y_pred))

Original Shape: (692703, 79)
After Cleaning Shape: (610492, 79)

Label Counts:
Label
BENIGN              416736
DoS Hulk            172846
DoS GoldenEye        10286
DoS slowloris         5385
DoS Slowhttptest      5228
Heartbleed              11
Name: count, dtype: int64
Training Data Shape: (488393, 78)
Testing Data Shape: (122099, 78)

First 10 Predictions:
NO - Normal
NO - Normal
NO - Normal
NO - Normal
NO - Normal
NO - Normal
NO - Normal
NO - Normal
NO - Normal
YES - Attack

Model Accuracy: 0.9993447939786566
Precision: 0.9989963456688455
Recall: 0.9989449305198147
F1 Score: 0.9989706374327697

Confusion Matrix:
 [[83200    39]
 [   41 38819]]

Full Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     83239
           1       1.00      1.00      1.00     38860

    accuracy                           1.00    122099
   macro avg       1.00      1.00      1.00    122099
weighted avg       1.00      1.00      1.

recall method 1

In [ ]:
# Get probabilities
y_prob = model.predict_proba(X_test)[:, 1]

# Lower threshold
threshold = 0.3
y_pred = (y_prob > threshold).astype(int)

print("Recall:", recall_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Recall: 0.9996911991765312

Confusion Matrix:
 [[83162    77]
 [   12 38848]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     83239
           1       1.00      1.00      1.00     38860

    accuracy                           1.00    122099
   macro avg       1.00      1.00      1.00    122099
weighted avg       1.00      1.00      1.00    122099



maximam recall method 2

In [ ]:
model = RandomForestClassifier(
    n_estimators=300,
    class_weight={0:1, 1:7},
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)
y_prob = model.predict_proba(X_test)[:, 1]
threshold = 0.3
y_pred = (y_prob > threshold).astype(int)
print("Recall:", recall_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Recall: 0.9997169325784869

Confusion Matrix:
 [[83170    69]
 [   11 38849]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     83239
           1       1.00      1.00      1.00     38860

    accuracy                           1.00    122099
   macro avg       1.00      1.00      1.00    122099
weighted avg       1.00      1.00      1.00    122099



friday working hours

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")
print(df.shape)
df.head()
df.info()

(225745, 79)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225745 entries, 0 to 225744
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0    Destination Port             225745 non-null  int64  
 1    Flow Duration                225745 non-null  int64  
 2    Total Fwd Packets            225745 non-null  int64  
 3    Total Backward Packets       225745 non-null  int64  
 4   Total Length of Fwd Packets   225745 non-null  int64  
 5    Total Length of Bwd Packets  225745 non-null  int64  
 6    Fwd Packet Length Max        225745 non-null  int64  
 7    Fwd Packet Length Min        225745 non-null  int64  
 8    Fwd Packet Length Mean       225745 non-null  float64
 9    Fwd Packet Length Std        225745 non-null  float64
 10  Bwd Packet Length Max         225745 non-null  int64  
 11   Bwd Packet Length Min        225745 non-null  int64  
 12   Bwd Packet Length Mean       2

In [ ]:
df.columns = df.columns.str.strip()
print(df)

        Destination Port  Flow Duration  Total Fwd Packets  \
0                  54865              3                  2   
1                  55054            109                  1   
2                  55055             52                  1   
3                  46236             34                  1   
4                  54863              3                  2   
...                  ...            ...                ...   
225740             61374             61                  1   
225741             61378             72                  1   
225742             61375             75                  1   
225743             61323             48                  2   
225744             61326             68                  1   

        Total Backward Packets  Total Length of Fwd Packets  \
0                            0                           12   
1                            1                            6   
2                            1                            6   
3  

In [ ]:
df.isnull().sum()
df = df.dropna()
print(df)

        Destination Port  Flow Duration  Total Fwd Packets  \
0                  54865              3                  2   
1                  55054            109                  1   
2                  55055             52                  1   
3                  46236             34                  1   
4                  54863              3                  2   
...                  ...            ...                ...   
225740             61374             61                  1   
225741             61378             72                  1   
225742             61375             75                  1   
225743             61323             48                  2   
225744             61326             68                  1   

        Total Backward Packets  Total Length of Fwd Packets  \
0                            0                           12   
1                            1                            6   
2                            1                            6   
3  

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
print(df['Label'].value_counts())
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Label'] = le.fit_transform(df['Label'])
print(df.shape)
df.head()


Label
DDoS      128014
BENIGN     95068
Name: count, dtype: int64
(223082, 79)


,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0


In [ ]:
# Convert all attacks to 1 and BENIGN to 0
df['Label'] = df['Label'].apply(lambda x: 0 if x == 0 else 1)
X = df.drop('Label', axis=1)
y = df['Label']
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42
)
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

print(y_pred)
for i in y_pred[:10]:   # print first 10 predictions
    if i == 1:
        print("YES - Attack")
    else:
        print("NO - Normal")
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)


Training data shape: (178465, 78)
Testing data shape: (44617, 78)
[0 1 0 ... 1 0 0]
NO - Normal
YES - Attack
NO - Normal
NO - Normal
NO - Normal
NO - Normal
YES - Attack
YES - Attack
YES - Attack
NO - Normal
Model Accuracy: 0.9999103480736042


**random forest metrics **

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Precision
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

# Recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

# F1 Score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Full Detailed Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Precision: 1.0
Recall: 0.9998441335775241
F1 Score: 0.9999220607147032
Confusion Matrix:
 [[18954     0]
 [    4 25659]]

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18954
           1       1.00      1.00      1.00     25663

    accuracy                           1.00     44617
   macro avg       1.00      1.00      1.00     44617
weighted avg       1.00      1.00      1.00     44617



In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Random Forest with higher weight for attacks
rf_model = RandomForestClassifier(
    n_estimators=100,
    class_weight={0:1, 1:3},
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

# Evaluation
print("Random Forest Results:")
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Random Forest Results:
Precision: 1.0
Recall: 0.9998441335775241
F1 Score: 0.9999220607147032
Confusion Matrix:
 [[18954     0]
 [    4 25659]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     18954
           1       1.00      1.00      1.00     25663

    accuracy                           1.00     44617
   macro avg       1.00      1.00      1.00     44617
weighted avg       1.00      1.00      1.00     44617



In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("Tuesday-WorkingHours.pcap_ISCX.csv")
df1 = pd.read_csv("Tuesday-WorkingHours.pcap_ISCX.csv")
print(df.shape)
df.head()
df.info()
print(df1.shape)
df1.head()
df1.info()

FileNotFoundError: [Errno 2] No such file or directory: 'Tuesday-WorkingHours.pcap_ISCX.csv'

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Tuesday-WorkingHours.pcap_ISCX.csv to Tuesday-WorkingHours.pcap_ISCX.csv
Saving Wednesday-workingHours.pcap_ISCX.csv to Wednesday-workingHours.pcap_ISCX.csv


In [ ]:
import os
print(os.listdir())

['.config', 'sample_data']


In [ ]:
import pandas as pd

# Get feature importance
importances = model.feature_importances_
feature_importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
})
# Sort by importance
feature_importance_df = feature_importance_df.sort_values(
    by='Importance',
    ascending=False
)
print(feature_importance_df.head(10))
import numpy as np
df.columns = df.columns.str.strip()
numeric_df = df.select_dtypes(include=['number'])
correlation_matrix = numeric_df.corr()
print(correlation_matrix)


                        Feature  Importance
6         Fwd Packet Length Max    0.093917
8        Fwd Packet Length Mean    0.086032
53         Avg Fwd Segment Size    0.075838
63            Subflow Fwd Bytes    0.071069
22                  Fwd IAT Std    0.054333
66       Init_Win_bytes_forward    0.048225
55          Fwd Header Length.1    0.042495
23                  Fwd IAT Max    0.040424
4   Total Length of Fwd Packets    0.039774
20                Fwd IAT Total    0.038628
                             Destination Port  Flow Duration  \
Destination Port                     1.000000       0.104748   
Flow Duration                        0.104748       1.000000   
Total Fwd Packets                   -0.045184       0.207008   
Total Backward Packets               0.007581       0.144591   
Total Length of Fwd Packets          0.553514       0.296798   
...                                       ...            ...   
Idle Mean                            0.130241       0.871492   
Idle

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=20)
X_pca = pca.fit_transform(X_scaled)

print("Original shape:", X_scaled.shape)
print("After PCA:", X_pca.shape)


Original shape: (223082, 78)
After PCA: (223082, 20)


**using SVM**

In [ ]:
import pandas as pd
import numpy as np
# Load Dataset
df = pd.read_csv("Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

print("Original Shape:", df.shape)

# Remove extra spaces in column names
df.columns = df.columns.str.strip()

# Remove null values
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

print("After Cleaning Shape:", df.shape)

# Encode Label column
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Label'] = le.fit_transform(df['Label'])

# Convert BENIGN to 0 and all attacks to 1
df['Label'] = df['Label'].apply(lambda x: 0 if x == 0 else 1)

print("Label Counts:\n", df['Label'].value_counts())

# Split Features and Target
X = df.drop('Label', axis=1)
y = df['Label']

# Feature Scaling (VERY IMPORTANT for SVM)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

# SVM MODEL

from sklearn.svm import SVC

model = SVC(kernel='rbf')   # You can try 'linear' also
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

print("First 10 Predictions:")
for i in y_pred[:10]:
    if i == 1:
        print("YES - Attack")
    else:
        print("NO - Normal")

# Accuracy
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("SVM Model Accuracy:", accuracy)

# PCA (Dimensionality Reduction)

from sklearn.decomposition import PCA

pca = PCA(n_components=20)
X_pca = pca.fit_transform(X_scaled)

print("Original Shape:", X_scaled.shape)
print("After PCA:", X_pca.shape)


Original Shape: (225745, 79)
After Cleaning Shape: (223082, 79)
Label Counts:
 Label
1    128014
0     95068
Name: count, dtype: int64
Training Shape: (178465, 78)
Testing Shape: (44617, 78)
First 10 Predictions:
NO - Normal
YES - Attack
NO - Normal
NO - Normal
NO - Normal
NO - Normal
YES - Attack
YES - Attack
YES - Attack
NO - Normal
SVM Model Accuracy: 0.9984086783064751
Original Shape: (223082, 78)
After PCA: (223082, 20)


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Precision
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

# Recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

# F1 Score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Full Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Precision: 0.9981314232326378
Recall: 0.9991037680707634
F1 Score: 0.9986173589608771
Confusion Matrix:
 [[18906    48]
 [   23 25640]]

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     18954
           1       1.00      1.00      1.00     25663

    accuracy                           1.00     44617
   macro avg       1.00      1.00      1.00     44617
weighted avg       1.00      1.00      1.00     44617



In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Train SVM with higher weight for attacks
svm_model = SVC(kernel='rbf', class_weight={0:1, 1:3}, probability=True)
svm_model.fit(X_train, y_train)

# Get probabilities
y_prob = svm_model.predict_proba(X_test)[:,1]

# Lower threshold to increase recall
y_pred = (y_prob > 0.4).astype(int)

# Evaluation
print("SVM Results:")
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

SVM Results:
Precision: 0.9981704231383082
Recall: 0.9991817012820013
F1 Score: 0.9986758062003427
Confusion Matrix:
 [[18907    47]
 [   21 25642]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     18954
           1       1.00      1.00      1.00     25663

    accuracy                           1.00     44617
   macro avg       1.00      1.00      1.00     44617
weighted avg       1.00      1.00      1.00     44617



In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(class_weight={0:1,1:3})
model.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 3})

In [ ]:
from sklearn.svm import LinearSVC

model = LinearSVC(class_weight={0:1,1:3})
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [ ]:
import pandas as pd

df_wed = pd.read_csv("Wednesday-workingHours.pcap_ISCX.csv")
df_wed.columns = df_wed.columns.str.strip()

print("Wednesday Unique Labels:")
print(df_wed['Label'].unique())

print("\nWednesday Label Counts:")
print(df_wed['Label'].value_counts())

Wednesday Unique Labels:
['BENIGN' 'DoS slowloris' 'DoS Slowhttptest' 'DoS Hulk' 'DoS GoldenEye'
 'Heartbleed']

Wednesday Label Counts:
Label
BENIGN              440031
DoS Hulk            231073
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Heartbleed              11
Name: count, dtype: int64


In [ ]:
import pandas as pd

df_fri = pd.read_csv("Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

# Fix column spaces
df_fri.columns = df_fri.columns.str.strip()

print("Friday Unique Labels:")
print(df_fri['Label'].unique())

print("\nFriday Label Counts:")
print(df_fri['Label'].value_counts())

Friday Unique Labels:
['BENIGN' 'DDoS']

Friday Label Counts:
Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64


What’s in Wednesday?
Wednesday Working Hours usually contains:
BENIGN
DoS Hulk
DoS GoldenEye
DoS Slowloris
DoS Slowhttptest
Heartbleed

👉 These are mostly DoS (Denial of Service) attacks.
🔎 What’s in Friday (Afternoon – DDoS)?
Friday usually contains:
BENIGN
DDoS

👉 This is a Distributed Denial of Service attack.
⚡ So Are They Similar?
✅ YES — They are similar in attack goal

Both DoS and DDoS:
Overload the server
Flood traffic
Make services unavailable
Target availability (CIA triad)